### PR TITLE
draft of topic 2 with todos, etc

### PR DESCRIPTION
**Pull request by xtitter**

### CODE REVIEW

**Comment by jmca93** [comment]
Nate, when I ran this "git pull https://github.com/xtitter/bjc-r gh-pages"
it's deleting a bunch of things like
cur/programming/intro...sprites-costumes.html. Is that right? I won't
commit these changes until I hear back from you

**Comment by jmca93** [comment]
nvm

**Comment by xtitter** [comment]
I'm not sure what was going on with that git commit of mine, 
unfortunately.  Things are ok now?

   <-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><->
   Nathaniel Titterton, Ph.D.                    nate@berkeley.edu
   Computer Science Education         U.C. Berkeley, 329 Soda Hall

**Comment by xtitter** [comment]
I added a quiz on composing with buggy blocks, and sent a pull request.

   <-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><->
   Nathaniel Titterton, Ph.D.                    nate@berkeley.edu
   Computer Science Education         U.C. Berkeley, 329 Soda Hall

**Pull request merged**
